In [1]:
import pandas as pd
import numpy as np

In [2]:
prof = pd.read_csv(r"C:\Users\Parsa\Downloads\full_prof_v4.csv")

In [3]:
prof.shape

(50659, 14)

In [10]:
prof[49399< prof.id]

,id,name,university,user_id,affiliation,v_email_at,interests,cited_by_all,cited_by_since_2020,h_index_all,h_index_since_2020,i10_index_all,i10_index_since_2020,yearly_data
49400,49400,Hoseyn Sayyaadi (ORCID: 0000-0003-1368-1426; S...,K. N. Toosi University of Technology,wfWq2IsAAAAJ,KN TOOSI University of Technology,kntu.ac.ir,"Energy, Modeling and optimization, Cavitation,...",6239,3699,48,38,105,95,"{'2010': 35, '2011': 76, '2012': 74, '2013': 1..."
49401,49401,Reza Kazemi,K. N. Toosi University of Technology,cPbr9GEAAAAJ,"PhD in Mechanical Engineering, Mechanical Engi...",kntu.ac.ir,System Dynamics and Control,5881,3237,42,28,134,89,"{'2004': 21, '2005': 25, '2006': 29, '2007': 5..."
49402,49402,Ali Asghar Alesheikh,K. N. Toosi University of Technology,vApZ2rgAAAAJ,"Professor in GIS, KN Toosi University of Techn...",kntu.ac.ir,Geospatial Information Science,5888,2998,35,26,104,67,"{'2007': 15, '2008': 46, '2009': 41, '2010': 1..."
49403,49403,Masoud Aliakbar Golkar,K. N. Toosi University of Technology,0X7yOtgAAAAJ,KN Toosi University of Technology,kntu.ac.ir,"Electric distribution systems, Renewable energ...",5669,3067,38,27,92,54,"{'2009': 32, '2010': 55, '2011': 102, '2012': ..."
49404,49404,Dr. M. Shariyat,K. N. Toosi University of Technology,CTXadHwAAAAJ,"Professor of Mechanical Engineering, KN Toosi ...",kntu.ac.ir,"Solid Mech., Plates & Shells, Smart Structures...",5442,2074,41,22,130,85,"{'2008': 21, '2009': 49, '2010': 93, '2011': 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50654,50968,Leila Emami-Meybodi,Iran University of Science and Technology,I-GCp64AAAAJ,Ph.D. Candidate at Iran University Science and...,ind.iust.ac.ir,"Operations resaerch, Optimization, Supply chai...",99,41,3,2,2,2,"{'2013': 3, '2014': 2, '2015': 12, '2016': 9, ..."
50655,50969,Seyed Mohammad kalantari,Iran University of Science and Technology,D0liAn8AAAAJ,Iran University of Science and Technology,metaleng.iust.ac.ir,Biomedical Engineering,99,49,2,2,2,2,"{'2015': 5, '2016': 12, '2017': 13, '2018': 12..."
50656,50970,Mansour Momeni,Iran University of Science and Technology,xqdbCDcAAAAJ,"Materials Science and Engineering, Iran Univer...",alumni.iust.ac.ir,"Nanostructured Thin Films, Functional Material...",100,58,4,4,4,2,"{'2015': 5, '2016': 3, '2017': 11, '2018': 11,..."
50657,50971,Yasaman Hosseinzadeh Dehaghani,Iran University of Science and Technology,qQmxv_0AAAAJ,"School of Chemical, Petroleum and Gas Engineer...",chemeng.iust.ac.ir,NaN,99,95,5,5,5,4,"{'2018': 1, '2019': 2, '2020': 6, '2021': 18, ..."
50658,50972,Omid Zandi,Iran University of Science and Technology,TyUB1d0AAAAJ,Iran university of science and technology,elec.iust.ac.ir,"control theory, power electronic, reinforcemen...",100,95,4,4,3,3,"{'2019': 4, '2020': 9, '2021': 10, '2022': 18,..."

In [15]:
prof.duplicated('name').count()

50659

In [17]:
duplicate_counts = prof['name'].value_counts() - 1

In [18]:
duplicates = duplicate_counts[duplicate_counts > 0]

In [19]:
duplicates

name
Hossein Mohammadi        9
Mohammad Salehi          8
Ali Ahmadi               7
Mohammad Sharifi         7
Mohammad Mohammadi       7
                        ..
Rouholah Zare Dorabei    1
Mohammad Tahmasebi       1
Alireza Shahidi          1
Farshid Nasiri           1
Sara Asadi               1
Name: count, Length: 1877, dtype: int64

In [20]:
prof[prof.duplicated()]

Empty DataFrame
Columns: [id, name, university, user_id, affiliation, v_email_at, interests, cited_by_all, cited_by_since_2020, h_index_all, h_index_since_2020, i10_index_all, i10_index_since_2020, yearly_data]
Index: []

In [21]:
df = pd.read_csv(r"C:\Users\Parsa\Downloads\final_dataset\final_articles.csv")

In [22]:
df.shape

(201405, 18)

In [23]:
df.head()

,id,title,authors,publication_date,journal,volume,issue,pages,publisher,total_citations,description,GS_link,article_link,external_link,scholar_articles,citation_bars,link_ids,subject
0,70,Timing of surgery following SARS‐CoV‐2 infecti...,COVIDSurg Collaborative,2021/6,Anaesthesia,76.0,6,748-758,Wiley-Blackwell Publishing Ltd.,588,Peri-operative SARS-CoV-2 infection increases ...,/citations?view_op=view_citation&hl=en&user=_C...,https://pure.au.dk/portal/en/publications/timi...,https://pure.au.dk/portal/files/273706648/Anae...,[{'title': 'Timing of surgery following SARS-C...,"[{'year': '2020', 'count': '2'}, {'year': '202...",0-116-55,Life Sciences & Biomedicine
1,284,SARS-CoV-2 infection and venous thromboembolis...,"Collaborative COVIDSurg, Collaborative GlobalSurg",2022,Anaesthesia,77.0,1,28-39,Association of Anaesthetists,109,SARS-CoV-2 has been associated with an increas...,/citations?view_op=view_citation&hl=en&user=_C...,https://boris.unibe.ch/162951/,https://boris.unibe.ch/162951/1/Anaesthesia_-_...,[{'title': 'SARS-CoV-2 infection and venous th...,"[{'year': '2021', 'count': '4'}, {'year': '202...",0-116,Life Sciences & Biomedicine
2,319,Effects of pre‐operative isolation on postoper...,"COVIDSurg Collaborative, GlobalSurg Collaborat...",2021/11,Anaesthesia,76.0,11,1454-1464,NaN,45,We aimed to determine the impact of pre‐operat...,/citations?view_op=view_citation&hl=en&user=_C...,https://associationofanaesthetists-publication...,https://associationofanaesthetists-publication...,[{'title': 'Effects of pre‐operative isolation...,"[{'year': '2021', 'count': '5'}, {'year': '202...",0-116-55,Life Sciences & Biomedicine
3,383,A new label-free immunosensor for detection of...,"Parviz Norouzi, Mohammad Nezamoddini, Mohammad...",2023/2/19,International Journal of Environmental Analyti...,103.0,3,546-560,Taylor & Francis,1,This work presents a new electrochemical immun...,/citations?view_op=view_citation&hl=en&user=_C...,https://www.tandfonline.com/doi/abs/10.1080/03...,NaN,[{'title': 'A new label-free immunosensor for ...,"[{'year': '2024', 'count': '1'}]",5600-0-34234,"Agricultural, Veterinary and Food Sciences"
4,395,Parameter identification of complex network dy...,"Arian Bakhtiarnia, Ali Fahim, Ehsan Maani Mian...",2021/6,Nonlinear Dynamics,104.0,4,3991-4005,Springer Netherlands,4,"Here, we present a novel approach called the “...",/citations?view_op=view_citation&hl=en&user=_C...,https://link.springer.com/article/10.1007/s110...,NaN,[{'title': 'Parameter identification of comple...,"[{'year': '2023', 'count': '3'}, {'year': '202...",0-763,Information and Computing Sciences

In [24]:
df.head().to_csv(r"C:\Users\Parsa\Downloads\sample_articles.csv")